name: spine_client
description: Dart-based client for Spine applications.
version: 0.1.0
homepage: https://spine.io
author: Spine Event Engine <spine-developers@teamdev.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  protobuf: ^0.14.4
  http: 0.12.0+2
  uuid: 2.0.2
  firebase: 5.0.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
