name: spine_client
description: Dart-based client for Spine applications.
version: 1.1.1-SNAPSHOT+1
homepage: https://spine.io
author: Spine Event Engine <spine-developers@teamdev.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  protobuf: 0.14.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
