name: Run integration tests

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Pull config
        run: git submodule update --init --recursive

      - name: Ensure test resource directory exists
        run: mkdir ./integration-tests/test-app/src/main/resources/
        shell: bash

      - name: Decrypt Firebase service account key
        run: ./config/scripts/decrypt.sh "$FIREBASE_SA_KEY" ./.github/keys/firebase-sa.json.gpg ./integration-tests/test-app/src/main/resources/spine-dev.json
        shell: bash
        env:
          FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}

      - name: Build project and run tests
        shell: bash
        run: ./gradlew integrationTest --stacktrace
